server.port=${SERVER_PORT:8080}

# Node role: "leader" or "follower"
node.role=${ROLE:leader}

# For leader: comma-separated follower URLs
node.follower-urls=${FOLLOWER_URLS:http://follower1:8080,http://follower2:8080,http://follower3:8080,http://follower4:8080}

# Quorum configuration (W and R values)
node.write-quorum=${WRITE_QUORUM_SIZE:5}
node.read-quorum=${READ_QUORUM_SIZE:1}

# Simulated delays (ms) ? do not change
node.write-delay-ms=200
node.read-delay-ms=50