server.port=${SCS_PORT:8081}

# AWS change base-url
cca.base-url=${CCA_BASE_URL:http://localhost:8080}
cca.authorize-path=/credit-card/authorize
cca.connect-timeout-ms=${CCA_CONNECT_TIMEOUT_MS:200}
cca.read-timeout-ms=${CCA_READ_TIMEOUT_MS:800}

# AWS change RMQ_HOST / RMQ_USER / RMQ_PASS / RMQ_QUEUE...
rmq.host=${RMQ_HOST:localhost}
rmq.port=${RMQ_PORT:5672}
rmq.username=${RMQ_USER:guest}
rmq.password=${RMQ_PASS:guest}
rmq.vhost=${RMQ_VHOST:/}

rmq.queue=${RMQ_QUEUE:orders_queue}
rmq.confirm-timeout-ms=${RMQ_CONFIRM_TIMEOUT_MS:5000}

rmq.pool.max-total=${RMQ_POOL_MAX_TOTAL:50}
rmq.pool.max-wait-ms=${RMQ_POOL_MAX_WAIT_MS:1000}

# JMX Confliction
spring.jmx.enabled=false

# Debug
logging.level.com.cs6650.scsservice=DEBUG
logging.level.org.springframework.context=DEBUG
